version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - API_BASE_URL=http://localhost:8000
      - LOG_LEVEL=INFO
      - UPLOAD_DIR=/app/shared/uploads
      - OUTPUT_DIR=/app/shared/output_logs
      - SQLITE_DB_PATH=/app/memory/agent_memory.db
      - CHROMA_DB_PATH=/app/memory/chroma_db
    volumes:
      - ./backend/shared:/app/shared
      - ./backend/memory:/app/memory
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy

volumes:
  shared_data:
  memory_data: 