version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Backend port
    volumes:
      - ./backend/data:/app/data  # For persistent data storage
      - ./backend/uploads:/app/uploads  # For file uploads
      - chroma_data:/app/data/chroma  # For chromadb persistence
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_API_KEY=AIzaSyAHKuJEhWqmjQbh8Q3wHupGtOyNmwzCXk8
      - CHROMADB_PERSIST_DIRECTORY=/app/data/chroma
      - PORT=8000
      - ALLOWED_ORIGINS=http://localhost:3000
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Frontend port
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_WS_URL=ws://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local 