version: '3.8'

services:
  mailer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Frontend port
      - "8000:8000"  # Backend port
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./data:/app/data  # For persistent data storage
    restart: unless-stopped

volumes:
  shared_data:
  memory_data: 