version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Backend port
    volumes:
      - ./backend/data:/app/data  # For persistent data storage
      - ./backend/uploads:/app/uploads  # For file uploads
      - chroma_data:/app/data/chroma  # For chromadb persistence
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local 